### ISSUE TITLE
Status on M1 Pro

### ISSUE THREAD

**Issue by Lumisilk** [MoustacheOff/AppleSilicon-Minecraft-Shaders#1]
Hi Moustache, I’m Lynn. Thanks for sharing this list.
I tested some on my M1 Pro MBP and would like to report on its support status. Seems your discord is not accepting the friend requests so I post them here.

MacBookPro 18,3
Apple M1 Pro
10 Cores CPU
32GB RAM
16 Cores Built-In GPU
**Test on external monitor with 4K resolution**

Minecraft 1.18.1
Forge 39.0.66
OptiFine_1.18.1_HD_U_H4
Graphics: Fast
Unlimited frame rate
All have default 1x settings (I think)

**Sildur’s Enhanced Default 1.3.1**
Fast: works at 40-60 fps
Fancy: 4 fps. And I can’t tell the graphics difference between the Fast version.

**Chocapic13 HighPerformance**
Low / Toaster: 70 fps, looks good.
BTW is it normal to be too dark at night? Barely see anything without the light. Is it a feature of Chocapic13?

**projectLuma 1.32**
around 30 fps, and doesn't render shadows properly like this:
![LUMA](https://user-images.githubusercontent.com/11924267/155648589-85be0d65-b943-4ad6-8368-9d3d73c39642.jpg)

**Sildurs Vibrant Shaders**
1.32 High: 4fps, unplayable
1.20 High/Medium/Lite: around 40 fps, looks good.

**KUDA Shaders 6.5.56**
25fps, but doesn't render shadows properly.

**SEUS Renewed (fixed version)**
12 fps. Doesn't render properly.

That’s all.

**Comment by ghost** [comment]
hi just a tip to get some more fps try lowering your render quality in optifine settings to .5x since otherwise you're playing at 4k which isn't really necessary for minecraft gaming.

**Comment by MoustacheOff** [comment]
@ribilynn Thanks so much for helping! I'm really sorry for not being able to answer earlier, it seems that GitHub sent me the notifications more than 2 weeks late 😅 . I also fixed the problem of friend requests on Discord.
I will update the list as soon as possible. 😄 
Thanks again for your support and contribution!
