### ISSUE TITLE
BSL Shaders

### ISSUE THREAD

**Issue by colingoodman** [MoustacheOff/AppleSilicon-Minecraft-Shaders#2]
[BSL Shaders](https://www.curseforge.com/minecraft/customization/bsl-shaders) version 7.0 and below work on Apple Silicon as per their Discord + confirmed on my m1 pro.

**Comment by MoustacheOff** [comment]
> [BSL Shaders](https://www.curseforge.com/minecraft/customization/bsl-shaders) version 7.0 and below work on Apple Silicon as per their Discord + confirmed on my m1 pro.

@colingoodman Thanks for sharing! I'll update the list soon.

**Comment by MoustacheOff** [comment]
https://bitslablab.com/bslshaders/#faqs
>  _There's something in BSL which seems to be incompatible with M1. I'm planning to fix this some point in the future._
