### ISSUE TITLE
ManyMC

### ISSUE THREAD

**Issue by carterlasalle** [MoustacheOff/AppleSilicon-Minecraft-Shaders#3]
ManyMC is a fork of MultiMC the Minecraft Launcher with native support for macOS arm64 (M1)!!!

https://github.com/MinecraftMachina/ManyMC

**Comment by MoustacheOff** [comment]
Updated README.md to mention ManyMC on commit [`90379cc`](https://github.com/MoustacheOff/AppleSilicon-Minecraft-Shaders/commit/90379cc395fcfa39678bb5fc8c87b0ba2f6f7688)
