### ISSUE TITLE
BSL doesn't work well

### ISSUE THREAD

**Issue by Bexin3** [MoustacheOff/AppleSilicon-Minecraft-Shaders#5]
This sometimes happens - fps lock to 4 and leaves. Also text is broken
![Screenshot 2022-08-24 at 10 00 32](https://user-images.githubusercontent.com/88098139/186366652-f7ff2c45-b7a9-49af-aa03-f77af9015765.jpeg)

**Comment by MoustacheOff** [comment]
This issue is not related to this repo. Please inform this bug to the BSL developer here: https://discord.com/invite/ZJd7jjA
